name = "Interpolations"
uuid = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
version = "0.16.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AxisAlgorithms = "13072b0f-2c55-5437-9ae7-d433b7a33950"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Ratios = "c84ed2f1-dad5-54f0-aa8e-dbefe2724439"
SharedArrays = "1a1011a3-84de-559e-8e89-a11a2f7dc383"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WoodburyMatrices = "efce3f68-66dc-5838-9240-27a6d6f5f9b6"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
InterpolationsUnitfulExt = "Unitful"
InterpolationsForwardDiffExt = "ForwardDiff"

[compat]
Adapt = "2, 3, 4.0"
AxisAlgorithms = "0.3, 1"
ChainRulesCore = "0.10, 1.0, 1.2, 1.3"
ForwardDiff = "0.10, 1.0"
JLArrays = "0.2"
OffsetArrays = "0.10, 0.11, 1.0.1"
Ratios = "0.3, 0.4"
StaticArrays = "0.12, 1"
Unitful = "1"
WoodburyMatrices = "0.4, 0.5, 1.0"
julia = "1.9"

[extras]
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
JLArrays = "27aeb0d3-9eb9-45fb-866b-73c2ecf80fcb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ColorVectorSpace", "DualNumbers", "JLArrays", "ForwardDiff", "Test", "Unitful", "Zygote"]
